spring:
  application:
    name: usian-item-service
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    url: jdbc:mysql://127.0.0.1:3306/usian?serverTimezone=GMT%2B8 #URL
    username: root #用户名
    password: root #密码
    type: com.alibaba.druid.pool.DruidDataSource #连接池类型
    druid:
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 默认 false 为 true 时 validationQuery 必须设为非空字符串
      # 【建议】配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，
      # testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: select 1

server:
  port: 8090 #端口
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #服务注册的地址
#hystrix的超时时间
hystrix:
  command:
  default:
  execution:
  timeout:
  enabled: true
  isolation:
  thread:
  timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000 #读取时间
  ConnectTimeout: 30000 #连接超时时间
  #开启eureka负载均衡策略enabled:true
  eureka:
    enabled: true #解决错误 com.netflix.client.ClientException: Load balancer does not have available server for client:usian-item-service





