spring:
  application:
    name: usian-content-service
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    url: jdbc:mysql://127.0.0.1:3306/usian?serverTimezone=GMT%2B8 #URL
    username: root #用户名
    password: root #密码
    type: com.alibaba.druid.pool.DruidDataSource #连接池类型
    druid:
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 默认 false 为 true 时 validationQuery 必须设为非空字符串
      # 【建议】配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，
      # testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: select 1
  redis:
    cluster:
      nodes:
        - 192.168.2.101:6379
        - 192.168.2.101:6380
        - 192.168.2.101:6381
        - 192.168.2.101:6382
        - 192.168.2.101:6383
        - 192.168.2.101:6384
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
#配置缓存首页大广告位的 key
PORTAL_AD_KEY: PORTAL_AD_KEY

server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#hystrix的超时时间
hystrix:
  enabled: true
  timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000 #读取时间
  ConnectTimeout: 30000 #连接超时时间
  #开启eureka负载均衡策略enabled:true
  eureka:
    enabled: true #解决错误 com.netflix.client.ClientException: Load balancer does not have available server for client:usian-item-service
#大广告位图片信息
AD_CATEGORY_ID: 89
AD_HEIGHT: 240
AD_WIDTH: 670
AD_HEIGHTB: 240
AD_WIDTHB: 550
