spring:
  application:
    name: usian-search-web
server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  #全局配置
  #请求连接的超时时间
ribbon:
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000
  #开启eureka负载均衡策略enabled:true
  eureka:
    enabled: true #解决错误 com.netflix.client.ClientException: Load balancer does not have available server for client:usian-item-service
